Repository OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW, pull requests merged in 2022-09, with the labels that each got.

#27 fixes drop down tile emitting a button event (single) when launching …
  include/classTile.h
  src/classes/classTile.cpp
  src/main.cpp
Labels: bug

#28 update thermostat tile (target/current temps) from "thermostat" object
  include/classTile.h
  include/globalDefines.h
  src/classes/classTile.cpp
  src/main.cpp
Labels: enhancement

#29 add option to set individual tile background
  include/classTile.h
  src/classes/classTile.cpp
  src/main.cpp
Labels: enhancement

#31 add option to disable a tile
  include/classTile.h
  src/classes/classTile.cpp
  src/main.cpp
Labels: enhancement

#34 moved keypad commands into tile payload
  include/classKeyPad.h
  src/classes/classKeyPad.cpp
  src/main.cpp
Labels: enhancement

#38 add TS_FEED tile style to show message feed
  include/classMessageFeed.h
  include/classPopUpContainer.h
  include/classTile.h
  include/globalDefines.h
  src/classes/classMessageFeed.cpp
  src/classes/classPopUpContainer.cpp
  src/classes/classTile.cpp
  src/main.cpp
  src/resources/ios_feed_60.c
Labels: enhancement

#39 allow to set single screen background color
  include/classScreen.h
  include/classTile.h
  include/classTileList.h
  src/classes/classScreen.cpp
  src/classes/classTile.cpp
  src/classes/classTileList.cpp
  src/main.cpp
Labels: bug, enhancement

#41 Panel locking
  include/classKeyPad.h
  include/globalDefines.h
  platformio.ini
  src/classes/classDropDown.cpp
  src/classes/classKeyPad.cpp
  src/main.cpp
Labels: enhancement

#42 add cmnd/ payloads for screen and tile removal
  src/main.cpp
Labels: enhancement

#43 symplified internal jsonColorRgb handling
  include/classScreen.h
  include/classTile.h
  src/classes/classScreen.cpp
  src/classes/classTile.cpp
  src/main.cpp
Labels: enhancement

#44 colorBg, screenColorBg and tileColorBg via cmnd/ and conf/
  src/main.cpp
Labels: enhancement

#45 BUGFIX : maintain heap usage on screen/tile creation/removal
  include/classScreen.h
  src/classes/classScreen.cpp
  src/classes/classScreenList.cpp
  src/classes/classTile.cpp
Labels: bug
